services:
  php:
    build:
        dockerfile: ./docker/php/Dockerfile
    container_name: phpunit-container
    volumes:
      - .:/app
    working_dir: /app
    command: "tail -f /dev/null"
    ports:
      - 9003:9003
