<?php

declare(strict_types=1);

namespace Phauthentic\CognitiveCodeAnalysis\Tests\Fixtures\CustomReporters;

use Phauthentic\CognitiveCodeAnalysis\Business\Churn\Report\ReportGeneratorInterface;
use Phauthentic\CognitiveCodeAnalysis\Config\CognitiveConfig;

/**
 * Config-aware custom text reporter for churn data testing
 */
class ConfigAwareChurnTextReporter implements ReportGeneratorInterface
{
    public function __construct(
        private readonly CognitiveConfig $config
    ) {
    }

    /**
     * @param array<string, array<string, mixed>> $classes
     */
    public function export(array $classes, string $filename): void
    {
        $content = $this->generateReport($classes);
        file_put_contents($filename, $content);
    }

    /**
     * @param array<string, array<string, mixed>> $classes
     */
    private function generateReport(array $classes): string
    {
        $output = "=== Config-Aware Churn Analysis Report ===\n";
        $output .= "Generated by ConfigAwareChurnTextReporter\n\n";

        $output .= "Configuration:\n";
        $output .= "Score Threshold: " . $this->config->scoreThreshold . "\n";
        $output .= "Group By Class: " . ($this->config->groupByClass ? 'Yes' : 'No') . "\n";
        $output .= "Show Only Methods Exceeding Threshold: " . ($this->config->showOnlyMethodsExceedingThreshold ? 'Yes' : 'No') . "\n\n";

        $output .= "Analysis Summary:\n";
        $output .= "Total Classes: " . count($classes) . "\n";

        $totalMethods = 0;
        foreach ($classes as $classData) {
            if (isset($classData['methods'])) {
                $totalMethods += count($classData['methods']);
            }
        }
        $output .= "Total Methods: " . $totalMethods . "\n\n";

        $output .= "Churn Analysis Results:\n";
        $output .= str_repeat("-", 50) . "\n";

        $aboveThresholdCount = 0;

        foreach ($classes as $className => $classData) {
            $score = $classData['score'] ?? 0;
            $isAboveThreshold = $score > $this->config->scoreThreshold;

            if ($isAboveThreshold) {
                $aboveThresholdCount++;
                $output .= "Class: " . $className . " [ABOVE THRESHOLD]\n";
            } else {
                $output .= "Class: " . $className . "\n";
            }

            $output .= "File: " . ($classData['file'] ?? 'Unknown') . "\n";
            $output .= "Score: " . ($classData['score'] ?? 'N/A') . "\n";
            $output .= "Churn: " . ($classData['churn'] ?? 'N/A') . "\n";
            $output .= "Times Changed: " . ($classData['timesChanged'] ?? 'N/A') . "\n";

            if (isset($classData['coverage'])) {
                $output .= "Coverage: " . ($classData['coverage'] ?? 'N/A') . "%\n";
            }

            if (isset($classData['riskLevel'])) {
                $output .= "Risk Level: " . ($classData['riskLevel'] ?? 'N/A') . "\n";
            }

            $output .= "\n";
        }

        $output .= "Classes Above Threshold (" . $this->config->scoreThreshold . "): " . $aboveThresholdCount . "\n";

        return $output;
    }
}
