name: Build and Release PHAR

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags'
        required: True
        type: boolean
jobs:
  build-phar:
    name: Build PHAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: json, fileinfo
        tools: composer

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build PHAR
      run: composer build-phar

    - name: Upload PHAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: phpcca.phar
        path: phpcca.phar

  release:
    name: Create Release
    needs: build-phar
    runs-on: ubuntu-latest

    steps:
    - name: Download PHAR artifact
      uses: actions/download-artifact@v4
      with:
        name: phpcca.phar

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: phpcca.phar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: true
